### ISSUE TITLE
Cuda 8, VS2105

### ISSUE THREAD

**Issue by crohkohl** [moderngpu/moderngpu#23]
Hi,

I am having trouble getting reduce_by_key to compile. I think there are some compiler issues.
My system is VS2015 with Cuda 8.

The following "__attribute__((aligned))" in tuple.hxx

![image](https://cloud.githubusercontent.com/assets/6941505/22250569/b07b770e-e247-11e6-83d9-dddc14152900.png)

makes the compiler choke.

The second problem is the __restrict__ keyword usage in meta.hxx:

![image](https://cloud.githubusercontent.com/assets/6941505/22250633/ef0cff38-e247-11e6-9faa-02fadb121a8d.png)

It seems, that the __restrict__keyword ist not allowed for type definitions. It throws this compiler error:

https://msdn.microsoft.com/en-us/library/097sy9kt.aspx

Removing problem 1 and all types that include __restrict__ works. However, I am not sure how this influences the functionality of the library.

Thanks for the great work!

**Comment by tarocco** [comment]
still running in to this problem :(

**Comment by csukuangfj** [comment]
I would suggest removing them.
See
https://github.com/k2-fsa/k2/pull/753/files#diff-4353b3f4a255465d55ae1d1126b935ddb7fbe27268e39638cc550f96d6a25953
