### ISSUE TITLE
Cannot compile moderngpu with clang as the CUDA compiler

### ISSUE THREAD

**Issue by srogatch** [moderngpu/moderngpu#43]
When using `clang-12` as the CUDA compiler and CUDA Toolkit 11.4.1, it complains about `PRAGMA_UNROLL` usages. It is defined as
```
#ifndef PRAGMA_UNROLL
#ifdef __CUDA_ARCH__
  #define PRAGMA_UNROLL #pragma PRAGMA_UNROLL
#else
  #define PRAGMA_UNROLL
#endif
#endif
```
in `meta.hxx`. This syntax seems supported by `nvcc` only.

**Comment by neoblizz** [comment]
@srogatch if you get a chance to confirm that v2.13 is fixes, please let me know in this issue. Closing it for now.
