### ISSUE TITLE
Error in building 

### ISSUE THREAD

**Issue by ullasAparanji** [moderngpu/moderngpu#44]
When I run make I get the following error:

demo/cities.cu(265): internal error: assertion failed: gen_paren_or_brace_dynamic_init: bad kind (cp_gen_be.c, line 21252 in gen_paren_or_brace_dynamic_init)

1 catastrophic error detected in the compilation of "demo/cities.cu".
Compilation aborted.
Aborted (core dumped)

I am not sure how to fix this. Any suggestions?

**Comment by neoblizz** [comment]
> When I run make I get the following error:
> 
> demo/cities.cu(265): internal error: assertion failed: gen_paren_or_brace_dynamic_init: bad kind (cp_gen_be.c, line 21252 in gen_paren_or_brace_dynamic_init)
> 
> 1 catastrophic error detected in the compilation of "demo/cities.cu". Compilation aborted. Aborted (core dumped)
> 
> I am not sure how to fix this. Any suggestions?

PR #47 adds support for cmake, and should fix this. You just have to add a cmake file for the demo, just like how I did for `tests` folder.
